apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: result
  name: result
  namespace: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - image: result
        name: result
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value:  /keys/key.json        
        ports:
        - containerPort: 80
          name: result
        volumeMounts:
          - name: keys
            mountPath: "/keys"
            readOnly: true
      volumes:
      - name: keys
        secret:
          secretName: pubsub-key-vote